// Generated by CoffeeScript 2.1.1
(function() {
  var i, j;

  for (i = j = 0; j > -10; i = --j) {
    console.log(i);
  }

  // {TileGrid,Tile,Rect} = require './tile-grid-matrix.coffee'
// global.log = console.log.bind(console)

// # som arbitrary array of items.
// items = [0...100].map (i)->
// 	n: i

// g = new TileGrid
// 	width: 4
// 	height: 4

// freeSpace = (item)->
// 	return g.addRow(g.height.item.height)

// # create grid tiles and create a new bound to decide where that item can go.
// for item in items

// 	tile = new Tile
// 		max_x: Math.floor(1+Math.random()*2)
// 		max_y: Math.floor(1+Math.random()*2)
// 		item: item

// 	bound = new Rect 
// 		min_x: 0
// 		max_x: g.rect.max_x
// 		min_y: g.full.max_y
// 		max_y: g.rect.max_y

// 	g.addItem(tile,bound)
// 	break

// # console.log g.item_list
// console.log g.matrix

// # freeSpace = (item,x,y)->
// # 	return g.freeSpace(x,y,item.w,item.h)

// for item in items
// 	min_x = null
// 	max_x = g.width
// 	min_y = g.height
// 	max_y = g.height

// 	g.addItemToMatrix(item,min_x,max_x,min_y,max_y,freeSpace)
// 	break

// console.log '--width--'

// console.log '4,1'
// console.log g.setWidth(4,1)

// console.log '5,-1'
// console.log g.setWidth(5,-1)

// console.log '5,-1'
// console.log g.setWidth(5,-1)

// console.log '4,1'
// console.log g.setWidth(4,1)

// console.log '2,-1'
// console.log g.setWidth(2,-1)

// console.log '6,1'
// console.log g.setWidth(6,1)

// console.log '7,-1'
// console.log g.setWidth(6,1)

// console.log '--height--'

// console.log '4,1'
// console.log g.setHeight(4,1)

// console.log '5,-1'
// console.log g.setHeight(5,-1)

// console.log '5,-1'
// console.log g.setHeight(5,-1)

// console.log '4,1'
// console.log g.setHeight(4,1)

// console.log '2,-1'
// console.log g.setHeight(2,-1)

// console.log '6,1'
// console.log g.setHeight(6,1)

// console.log '7,-1'
// console.log g.setHeight(6,1)

}).call(this);
